"""initial migration

Revision ID: 932da2381324
Revises: 
Create Date: 2024-04-26 13:19:27.133729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932da2381324'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('hashtag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_college'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('college')
    # ### end Alembic commands ###
