"""a third migration

Revision ID: c9d54129235b
Revises: b80b70af5b0e
Create Date: 2024-04-26 22:51:42.731754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d54129235b'
down_revision = 'b80b70af5b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('joke', sa.String(length=100), nullable=True),
    sa.Column('memory', sa.String(length=50), nullable=True),
    sa.Column('hashtag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memories')
    # ### end Alembic commands ###
